spring:
  datasource:
    url: jdbc:h2:mem:test_db
  jpa:
    hibernate:
      ddl-auto: validate
commerce:
  server:
    port: 15002
---
spring:
  config:
    activate:
      on-profile: server
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
---
spring:
  config:
    activate:
      on-profile: transaction-client
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
commerce:
  server:
    host: server
  client:
    request:
      count: 100
      delay:
        between: 5000
---
spring:
  config:
    activate:
      on-profile: report-client
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
commerce:
  server:
    host: server
  client:
    request:
      count: 10
      delay:
        between: 30000
      report:
        duration: 30