spring:
  datasource:
    url: jdbc:h2:mem:test_db
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
---
spring:
  config:
    activate:
      on-profile: server
  jpa:
    hibernate:
      ddl-auto: none
commerce:
  server:
    available:
      time: 60
---
spring:
  config:
    activate:
      on-profile: client
  jpa:
    hibernate:
      ddl-auto: none
---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create-drop