version: '1'
services:
  server:
    container_name: server
    image: commerce:1.5
    environment:
      - SPRING_PROFILES_ACTIVE=server
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      commerce:
    depends_on:
      - db
  transaction-client:
    container_name: transaction-client
    image: commerce:1.5
    environment:
      - SPRING_PROFILES_ACTIVE=transaction-client
    networks:
      commerce:
    depends_on:
      - server
  report-client:
    container_name: report-client
    image: commerce:1.5
    environment:
      - SPRING_PROFILES_ACTIVE=report-client
    networks:
      commerce:
    depends_on:
      - server
  db:
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      commerce:
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local

networks:
  commerce: