version: '1'
services:
  server:
    container_name: server
    image: commerce:0.1
    environment:
      - SPRING_PROFILES_ACTIVE=server
    networks:
      commerce:
    depends_on:
      - db
  client:
    container_name: client
    image: commerce:0.1
    environment:
      - SPRING_PROFILES_ACTIVE=client
    networks:
      commerce:
    depends_on:
      - server
  db:
    container_name: db
    build:
      context: .
      dockerfile: db/Dockerfile
    restart: always
    ports:
      - '5432:5432'
    networks:
      commerce:
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local

networks:
  commerce: