version: '1'
services:
  server:
    container_name: server
    image: commerce:1.3
    environment:
      - SPRING_PROFILES_ACTIVE=server
    networks:
      commerce:
    depends_on:
      - db
  transaction-client:
    container_name: transaction-client
    image: commerce:1.3
    environment:
      - SPRING_PROFILES_ACTIVE=transaction-client
    networks:
      commerce:
    depends_on:
      - server
  report-client:
    container_name: report-client
    image: commerce:1.3
    environment:
      - SPRING_PROFILES_ACTIVE=report-client
    networks:
      commerce:
    depends_on:
      - server
  db:
    container_name: db
    build:
      context: .
      dockerfile: db/Dockerfile
    restart: always
    ports:
      - '5432:5432'
    networks:
      commerce:
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local

networks:
  commerce: