CREATE TABLE PAYMENT_METHOD
(
    ID                 SERIAL        PRIMARY KEY,
    NAME               VARCHAR(255)     NOT NULL,
    POINTS_MODIFIER    DOUBLE PRECISION NOT NULL,
    PRICE_MODIFIER_MAX DOUBLE PRECISION NOT NULL,
    PRICE_MODIFIER_MIN DOUBLE PRECISION NOT NULL
);

CREATE TABLE TRANSACTION
(
    ID              SERIAL        PRIMARY KEY,
    ADDITIONAL_ITEM VARCHAR(255),
    CUSTOMER_ID     BIGINT           NOT NULL,
    DATE_TIME       TIMESTAMP        NOT NULL,
    PAYMENT_METHOD  VARCHAR(255)     NOT NULL,
    PRICE           DOUBLE PRECISION NOT NULL,
    PRICE_MODIFIER  DOUBLE PRECISION NOT NULL
);

INSERT INTO PAYMENT_METHOD (ID, NAME, POINTS_MODIFIER, PRICE_MODIFIER_MAX, PRICE_MODIFIER_MIN)
VALUES (1, 'CASH', 0.9, 1.0, 0.05);
